# Generated by Django 5.0.6 on 2026-06-21 18:10

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='TrainingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('incident_report', 'Incident Report'), ('search_warrant', 'Search Warrant'), ('arrest_warrant', 'Arrest Warrant')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('raw_text', models.TextField(blank=True)),
                ('is_indexed', models.BooleanField(default=False)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(db_index=True, max_length=30)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_engine.trainingdocument')),
            ],
            options={
                'db_table': 'document_chunks',
                'ordering': ['training_doc_id', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingdocument',
            index=models.Index(fields=['doc_type', 'is_indexed'], name='training_do_doc_typ_c40838_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
