# Generated by Django 5.0.6 on 2026-07-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('jurisdiction_type', models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('municipal', 'Municipal/County')], default='state', max_length=50)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('court_name', models.CharField(blank=True, max_length=255)),
                ('judicial_district', models.CharField(blank=True, max_length=255)),
                ('division', models.CharField(blank=True, max_length=100)),
                ('court_caption', models.CharField(blank=True, max_length=255)),
                ('judge_title', models.CharField(blank=True, max_length=100)),
                ('prosecuting_authority', models.CharField(blank=True, max_length=255)),
                ('case_number_format', models.CharField(blank=True, max_length=100)),
                ('ori', models.CharField(blank=True, max_length=50)),
                ('default_legal_citations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
                'db_table': 'agencies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='The jurisdiction configuration for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='accounts.agency'),
        ),
    ]
