# Generated by Django 5.0.6 on 2026-07-18 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agency_user_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurisdictionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Georgia — State"', max_length=255, unique=True)),
                ('jurisdiction_type', models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('municipal', 'Municipal/County')], max_length=50)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('default_legal_citations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Jurisdiction Profiles',
                'db_table': 'jurisdiction_profiles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='requires_prosecutor_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='requires_supervisor_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='seal_image_key',
            field=models.CharField(blank=True, help_text='Storage key for the agency seal/logo (utils.storage).', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='jurisdiction_profile',
            field=models.ForeignKey(blank=True, help_text='Shared state/federal defaults (citations, formatting) this agency inherits.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='accounts.jurisdictionprofile'),
        ),
    ]
