# Generated by Django 5.0.6 on 2026-07-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jurisdictionprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified_by',
        ),
    ]
