# Generated by Django 5.0.6 on 2026-06-20 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=550, unique=True)),
                ('post_type', models.CharField(choices=[('text', 'Text Only'), ('text_image', 'Text + Image'), ('text_video', 'Text + Video'), ('text_image_video', 'Text + Image + Video'), ('image', 'Image Only'), ('video', 'Video Only')], default='text', max_length=30)),
                ('category', models.CharField(choices=[('law_enforcement', 'Law Enforcement'), ('technology', 'Technology'), ('ai', 'Artificial Intelligence'), ('legal_updates', 'Legal Updates'), ('training', 'Training & Education'), ('policy', 'Policy & Procedure'), ('general', 'General')], default='general', max_length=30)),
                ('content', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('cover_image', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Uploaded Video'), ('video_url', 'Embedded Video URL'), ('document', 'Document')], max_length=20)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('video_url', models.URLField(blank=True)),
                ('embed_html', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('thumbnail_s3_key', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='blog.blogpost')),
            ],
            options={
                'db_table': 'blog_media',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published', 'published_at'], name='blog_posts_is_publ_4325e6_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category'], name='blog_posts_categor_d08396_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['post_type'], name='blog_posts_post_ty_f0f8e9_idx'),
        ),
    ]
