import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const sections = [
  ['1. Information We Collect', <><p>KLYVOREK may process account information such as name, agency, professional email address, credentials, subscription information, role, and permissions. It may also process IP addresses, device and browser information, login activity, security events, system activity, and audit logs.</p><p>Authorized users may submit incident facts, investigative narratives, warrant application facts, case information, and other authorized documentation. This information may be sensitive or criminal justice-related.</p></>],
  ['2. How Information Is Used', <p>Information is processed to provide requested documentation services, generate AI-assisted drafts, maintain and authenticate accounts, provide support, detect unauthorized access, maintain audit records, improve reliability, and meet contractual or legal obligations.</p>],
  ['3. AI Processing', <><p>KLYVOREK uses artificial intelligence to organize and structure user-provided information.</p><p className="font-semibold text-gray-900">The user provides the facts. AI assists with structure. The law enforcement professional controls and approves the final document.</p><p>AI-generated content may contain errors, omissions, unsupported inferences, or inaccurate language. Users must independently review all content before relying upon, submitting, signing, swearing to, exporting, or otherwise using it.</p></>],
  ['4. Criminal Justice Information and Sensitive Data', <p>Agencies are responsible for determining whether submitted information is CJI, CHRI, personally identifiable information, protected investigative information, or other restricted data. Such information may be used only when the agency determines that the deployment, configuration, contracts, and procedures satisfy applicable legal, CJIS, security, and policy requirements.</p>],
  ['5. Safeguards and Access Controls', <p>Depending on deployment and subscription configuration, safeguards may include authentication, role-based access, encryption, customer-data separation, security logging, audit trails, monitoring, secure infrastructure, and administrative controls. Specific controls vary by deployment and contract. No information system can guarantee absolute security.</p>],
  ['6. AI Model Training', <p>Unless expressly authorized in a separate written agreement, KLYVOREK does not intentionally use agency-submitted reports, case narratives, warrant facts, or CJI to train publicly available general-purpose AI models. Third-party processing remains governed by applicable provider contracts and technical controls.</p>],
  ['7. Retention and Agency Records', <p>Information is retained only as reasonably necessary to provide services, maintain security and auditability, resolve disputes, satisfy contracts, or comply with the law. Agencies remain responsible for their official retention, evidence, discovery, and public-record obligations. Deletion from KLYVOREK does not alter those obligations.</p>],
  ['8. Disclosure', <p>KLYVOREK does not sell law enforcement case information. Information may be disclosed to provide contracted infrastructure, protect system security, investigate misuse, comply with valid legal processes, protect the rights, property, or safety of KLYVOREK and our users, or complete a lawful business transaction, subject to strict confidentiality protections.</p>],
  ['9. Ownership and Control', <p>Between KLYVOREK and a subscribing agency, the agency retains its rights in submitted information. KLYVOREK receives only the limited rights reasonably necessary to provide the contracted services.</p>],
  ['10. Cookies and Analytics', <p>The public website may use cookies or similar technologies for essential functionality, security, analytics, and performance. Sensitive case information is not intentionally used for advertising.</p>],
  ['11. Privacy Requests and Children', <p>Requests about agency-controlled records should generally be directed to the relevant agency. KLYVOREK is a professional law enforcement technology service and is not intended for children.</p>],
  ['12. Changes and Contact', <p>Policy Updates: Material changes will be reflected in this policy. We will provide additional notice to users when appropriate. Questions about this policy or suspected unauthorized access may be sent to <a className="text-blue-600 underline" href="mailto:klyvorek@gmail.com">klyvorek@gmail.com</a>.</p>],
]

export default function PrivacyPolicy() {
  return <div className="min-h-screen flex flex-col"><Navbar /><main className="flex-1 bg-gray-50 py-16"><article className="max-w-4xl mx-auto bg-white border border-gray-200 rounded-2xl shadow-sm px-6 sm:px-10 py-10"><p className="text-blue-600 text-sm font-semibold uppercase tracking-wider">Legal</p><h1 className="text-4xl font-bold text-gray-900 mt-2">KLYVOREK Privacy Policy</h1><p className="text-sm text-gray-500 mt-3">Effective August 11, 2026</p><p className="mt-8 text-gray-600 leading-relaxed">American Academy of Advanced Thinking, LLC, doing business as KLYVOREK, provides an AI-assisted documentation platform for authorized law enforcement and public-safety use. This policy explains how information is collected, used, stored, disclosed, and protected.</p><div className="mt-10 space-y-9">{sections.map(([title, body]) => <section key={title}><h2 className="text-xl font-bold text-gray-900 mb-3">{title}</h2><div className="space-y-3 text-gray-600 leading-relaxed">{body}</div></section>)}</div><div className="mt-10 pt-6 border-t text-sm text-gray-500">KLYVOREK · American Academy of Advanced Thinking, LLC · Metro Atlanta, Georgia 30106</div></article></main><Footer /></div>
}
