import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const terms = [
  ['1. Purpose', 'KLYVOREK is an AI-assisted documentation tool for authorized law-enforcement professionals. Available features may include incident reports, investigative narratives, warrant application drafts, affidavits, and administrative documentation. KLYVOREK is not a substitute for professional judgment, supervision, prosecution, legal counsel, or judicial determination.'],
  ['2. Mandatory Human Verification', 'An authorized professional must independently review every AI-assisted document before it is relied upon, submitted, signed, sworn to, exported, transmitted, or made part of an official record. Users remain responsible for facts, names, dates, locations, quotations, evidence, citations, offense elements, probable cause, scope, particularity, nexus, attachments, and legal sufficiency.'],
  ['3. No Fabrication', 'Users must not use KLYVOREK to fabricate evidence, probable cause, witness statements, confessions, investigative findings, observations, allegations, attribution, or other material facts.'],
  ['4. Warrant Applications', 'KLYVOREK may organize user-provided information into search or arrest warrant application drafts. It does not determine probable cause, issue warrants, or guarantee compliance with constitutional, statutory, procedural, prosecutorial, local, or judicial requirements.'],
  ['5. No Legal Advice', 'KLYVOREK does not provide legal advice or establish an attorney-client relationship. Explanations, flags, citations, and suggested language are informational and assistive only.'],
  ['6. No Autonomous Enforcement Decisions', 'KLYVOREK must not be the sole basis for arrest, detention, search, seizure, use of force, charging, probable cause, reasonable suspicion, targeting, threat determinations, guilt, sentencing, discipline, or decisions affecting constitutional rights.'],
  ['7. Authorized Users and Agency Policy', 'Users must provide accurate registration information, protect credentials, and ensure that their agency authorizes use consistent with law, policy, records, privacy, evidence, discovery, procurement, and security requirements.'],
  ['8. CJIS and CJI', 'Security features may support agency requirements, but CJIS compliance depends on deployment architecture, configuration, contracts, personnel, devices, networks, agency practices, and the information processed. Each agency must perform its own security, legal, procurement, and compliance review.'],
  ['9. AI Limitations', 'Generative AI may produce incorrect, incomplete, unsupported, outdated, or misleading content. Output must be treated as a draft requiring professional verification.'],
  ['10. Prohibited Uses', 'The service may not be used to falsify records, misrepresent AI text as an independently observed fact, access information without authorization, violate rights, circumvent controls, conduct unlawful surveillance, harass or discriminate unlawfully, facilitate crime, upload malware, or attempt unauthorized access.'],
  ['11. Ownership', 'KLYVOREK and its licensors retain ownership of the platform and proprietary technology. Customers retain their rights in submitted information, subject to the limited rights needed to provide the service.'],
  ['12. Availability and Changes', 'Features may be updated, suspended, or discontinued. KLYVOREK does not guarantee uninterrupted or error-free service.'],
  ['13. Subscription and Payment', 'Paid subscriptions are billed under the terms shown at purchase or in an agency agreement. Unless otherwise stated in writing, fees are non-refundable except where required by law.'],
  ['14. Disclaimer', 'TO THE MAXIMUM EXTENT PERMITTED BY LAW, KLYVOREK IS PROVIDED AS IS AND AS AVAILABLE. KLYVOREK DOES NOT WARRANT THAT AI CONTENT WILL BE ERROR-FREE, COMPLETE, LEGALLY SUFFICIENT, ADMISSIBLE, ACCURATE, OR APPROVED BY ANY AUTHORITY.'],
  ['15. Liability and Government Customers', 'To the maximum extent permitted by law, KLYVOREK is not liable for indirect, special, consequential, exemplary, or punitive damages arising from use of the service. Government-specific obligations, sovereign immunity, indemnification, public records, procurement, security, and governing-law terms are controlled by applicable law and separately executed agreements.'],
  ['16. Suspension', 'Access may be suspended to protect security, investigate unauthorized activity, prevent unlawful use, address material violations, or comply with law.'],
  ['17. Governing Law', 'These Terms are governed by Georgia law, without regard to conflict-of-law rules, except where applicable law or a separately executed government agreement requires otherwise. Venue is Cobb County, Georgia, unless otherwise required.'],
  ['18. Entire Agreement and Contact', 'These Terms, the Privacy Policy, subscription terms, and any separately executed agreement govern use of KLYVOREK. Questions may be sent to klyvorek@gmail.com.'],
]

export default function TermsOfService() {
  return <div className="min-h-screen flex flex-col"><Navbar /><main className="flex-1 bg-gray-50 py-16"><article className="max-w-4xl mx-auto bg-white border border-gray-200 rounded-2xl shadow-sm px-6 sm:px-10 py-10"><p className="text-blue-600 text-sm font-semibold uppercase tracking-wider">Legal</p><h1 className="text-4xl font-bold text-gray-900 mt-2">KLYVOREK Terms of Service</h1><p className="text-sm text-gray-500 mt-3">Effective August 11, 2026 · Last updated August 11, 2026</p><p className="mt-8 text-gray-600 leading-relaxed">By accessing KLYVOREK, the user and, where applicable, the user's agency agree to these Terms.</p><div className="mt-10 space-y-8">{terms.map(([title, text]) => <section key={title}><h2 className="text-xl font-bold text-gray-900 mb-3">{title}</h2><p className="text-gray-600 leading-relaxed">{text}</p></section>)}</div><div className="mt-10 pt-6 border-t text-sm text-gray-500">KLYVOREK · American Academy of Advanced Thinking, LLC · Metro Atlanta, Georgia 30106 · <a className="text-blue-600 underline" href="mailto:klyvorek@gmail.com">klyvorek@gmail.com</a></div></article></main><Footer /></div>
}
