# Generated by Django 5.0.6 on 2026-06-20 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('incident_report', 'Incident Report'), ('search_warrant', 'Search Warrant'), ('arrest_warrant', 'Arrest Warrant')], max_length=30)),
                ('case_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('form_data', models.JSONField()),
                ('ai_narrative', models.TextField(blank=True)),
                ('narrative_style', models.CharField(choices=[('first_person', 'First Person (I, my)'), ('third_person', 'Third Person (Officer name)')], default='first_person', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('s3_pdf_key', models.CharField(blank=True, max_length=500)),
                ('s3_docx_key', models.CharField(blank=True, max_length=500)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generated_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'doc_type'], name='generated_d_user_id_7503b0_idx'), models.Index(fields=['case_number'], name='generated_d_case_nu_3604ec_idx'), models.Index(fields=['status'], name='generated_d_status_ec9bb0_idx')],
            },
        ),
    ]
