# Generated by Django 5.0.6 on 2026-06-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='leak_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
