# Generated by Django 5.0.6 on 2026-07-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_generateddocument_leak_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='quality_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
