# Generated by Django 5.0.6 on 2026-07-18 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jurisdictionprofile_and_more'),
        ('documents', '0003_generateddocument_quality_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='narrative_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='prosecutor_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='prosecutor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='prosecutor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='prosecutor_reviewed_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='review_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending_supervisor', 'Pending Supervisor Review'), ('pending_prosecutor', 'Pending Prosecutor Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=30),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='signature_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='supervisor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='supervisor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='supervisor_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WarrantTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('search_warrant', 'Search Warrant'), ('arrest_warrant', 'Arrest Warrant')], max_length=30)),
                ('section_key', models.CharField(choices=[('affidavit_intro', 'Affidavit Introduction'), ('nexus_closing', 'Nexus / Probable Cause Closing (search warrants)'), ('elements_closing', 'Elements / Probable Cause Closing (arrest warrants)')], max_length=30)),
                ('jurisdiction_type', models.CharField(blank=True, choices=[('federal', 'Federal'), ('state', 'State'), ('municipal', 'Municipal/County')], max_length=50)),
                ('template_text', models.TextField(help_text='Pre-approved legal language with {placeholder} tokens. Have counsel review before use on a real filing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warrant_templates', to='accounts.agency')),
                ('jurisdiction_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warrant_templates', to='accounts.jurisdictionprofile')),
            ],
            options={
                'db_table': 'warrant_templates',
                'indexes': [models.Index(fields=['doc_type', 'section_key'], name='warrant_tem_doc_typ_daac67_idx')],
            },
        ),
    ]
