# Generated by Django 5.0.6 on 2026-07-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_is_verified_remove_user_verified_at_and_more'),
        ('documents', '0005_seed_warrant_templates'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='warranttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('agency__isnull', False)), fields=('agency', 'doc_type', 'section_key'), name='unique_warranttemplate_agency_scope'),
        ),
        migrations.AddConstraint(
            model_name='warranttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('jurisdiction_profile__isnull', False)), fields=('jurisdiction_profile', 'doc_type', 'section_key'), name='unique_warranttemplate_jurisdiction_scope'),
        ),
        migrations.AddConstraint(
            model_name='warranttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('agency__isnull', True), ('jurisdiction_profile__isnull', True)), fields=('doc_type', 'section_key', 'jurisdiction_type'), name='unique_warranttemplate_global_scope'),
        ),
    ]
