# Generated by Django 5.0.6 on 2026-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='can_regenerate',
        ),
        migrations.AddField(
            model_name='plan',
            name='warrant_document_limit',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Search + arrest warrants per month, combined. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='warrants_generated_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='document_limit',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Incident reports per month. Leave blank for unlimited.', null=True),
        ),
    ]
