# Generated by Django 5.0.6 on 2026-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_plan_can_regenerate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='arrest_warrants_generated_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='search_warrants_generated_this_month',
            field=models.IntegerField(default=0),
        ),
    ]
